[package]
authors = ["Fran√ßois Laignel <fengalin@free.fr>"]
description = "metadata modules for media-toc"
edition = '2018'
homepage = "https://github.com/fengalin/media-toc"
keywords = ["multimedia", "chapter", "table-of-contents", "gtk3", "gstreamer"]
license = "MIT"
name = "media-toc-metadata"
readme = "README.md"
repository = "https://github.com/fengalin/media-toc"
version = "0.7.99"

[dependencies]
gettext-rs = { version = "0.5", features = ["gettext-system"] }
glib = "0.10"
gstreamer = { version = "0.16", features = ["v1_10"] }
lazy_static = "1"
log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }
nom = "5"
